# Generated by Django 3.2.5 on 2021-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'sofa'), ('C', 'chair'), ('T', 'table')], max_length=2),
        ),
    ]
